### PR TITLE
electronic url text

### PR DESCRIPTION
**Pull request by tampakis**
Advances pulibrary/orangelight#179 and pulibrary/orangelight#35

### CODE REVIEW

**Comment by jpstroop** [comment]
Do you think the URL should show the protocol as well?

**Comment by tampakis** [comment]
I thought it would be safer to exclude it because some of the urls might not include the protocol.

**Comment by tampakis** [comment]
``` ruby
jruby-1.7.19 :010 > URI.parse('princeton.edu/blah').scheme
 => nil 
```

**Comment by jpstroop** [comment]
Are there URLs in the 856 without a protocol?

**Comment by tampakis** [comment]
I'm not sure if there are any 856s without a protocol.

I don't think it's a good idea to include the protocol in the url becuase users might think the anchor text we provide is the actual url to access the work. I'm not sure stripping the protocol is enough to solve that, but I think it's less misleading.

**Comment by jpstroop** [comment]
:ok:

**Pull request merged**
